### PR TITLE
chore(playroom): Adds responsive width

### PR DESCRIPTION
**Pull request by caseymhunt**
This adds another width option to the Playroom config which uses the CSS
`calc` function to create a responsive window width. It's ugly but it
works.

Demo of it working:
squishy playroom

### CODE REVIEW

**Review by nearbycoder — COMMENTED** [review]
Should the package lock be updated?

**Comment by caseymhunt** [comment]
> Should the package lock be updated?

Just noticing that myself. I've wiped out the `node_modules` folder a few times for other reasons but nothing has changed in package.json - it must be some patch/minor differences. Assuming no weirdness from Chromatic, should be ok?

**Review by nearbycoder — APPROVED** [review]
LGTM!

**Review by nearbycoder — APPROVED** [review]
👍

**Pull request merged**
