### PR TITLE
Add the correct syntax to switch to __css

### PR DESCRIPTION
**Pull request by nearbycoder**
[SPIKE: Swap `sx` for `__css` in components](https://app.clubhouse.io/firehydrant/story/19036/spike-swap-sx-for-css-in-components)

### CODE REVIEW

**Review by caseymhunt — APPROVED** [review]
👍🏼

**Comment by caseymhunt** [comment]
(for posterity) visual checks conducted manually until snapshot testing can be re-enabled on Chromatic.

**Comment by nearbycoder** [comment]
@caseymhunt you have a timeline for when visual checks will be back. I am fine with waiting for that to get this merged in

**Comment by caseymhunt** [comment]
> @caseymhunt you have a timeline for when visual checks will be back. I am fine with waiting for that to get this merged in

Tickets are filed, requests are made. Next week at the earliest at this point but honestly, I'm not sure.

**Comment by caseymhunt** [comment]
We've discovered an issue with our spacing primitives and will address this in a separate issue/PR.

**Pull request merged**
